// <auto-generated />
using System;
using ASM.Appdatacontext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASM.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASM.Models.Game_Mode", b =>
                {
                    b.Property<int>("GameMode_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameMode_id"));

                    b.Property<string>("GameMode_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameMode_id");

                    b.ToTable("Game_Modes", (string)null);
                });

            modelBuilder.Entity("ASM.Models.Items", b =>
                {
                    b.Property<int>("Item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Item_id"));

                    b.Property<int?>("Exp")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Item_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Items_type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Item_id");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("ASM.Models.Player", b =>
                {
                    b.Property<int>("Player_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Player_id"));

                    b.Property<string>("Character_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Exp")
                        .HasColumnType("int");

                    b.Property<int?>("Food")
                        .HasColumnType("int");

                    b.Property<int?>("Health")
                        .HasColumnType("int");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Player_id");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("ASM.Models.Player_GameModeController", b =>
                {
                    b.Property<int>("Player_GameMode_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Player_GameMode_id"));

                    b.Property<int?>("GameMode_id")
                        .HasColumnType("int");

                    b.Property<int?>("Player_id")
                        .HasColumnType("int");

                    b.HasKey("Player_GameMode_id");

                    b.ToTable("Player_GameModeController", (string)null);
                });

            modelBuilder.Entity("ASM.Models.Player_Resources", b =>
                {
                    b.Property<int>("Player_Resoucers_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Player_Resoucers_id"));

                    b.Property<int?>("Player_id")
                        .HasColumnType("int");

                    b.Property<int?>("Resources_id")
                        .HasColumnType("int");

                    b.HasKey("Player_Resoucers_id");

                    b.ToTable("Player_Resources", (string)null);
                });

            modelBuilder.Entity("ASM.Models.Resources", b =>
                {
                    b.Property<int>("Resources_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Resources_id"));

                    b.Property<string>("Resources_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Resources_id");

                    b.ToTable("ResourcesController", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
